spring:
  datasource:
    url: jdbc:h2:mem:migration;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
    user: sa
    password: password
  security:
    user:
      name: user
      password: user
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
